import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased"`}>
        <main className="grid grid-rows-[auto,1fr,auto] gap-4 p-4 overflow-auto">{children}</main>

        {/* fixed on the bottom */}
        <footer className="text-center text-sm text-gray-500 py-4">
          View Source from GitHub Repository{' '}
          <a
            href="https://github.com/chanhee-park/speech-recognition-test"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-500 hover:underline"
          >
            chanhee-park/speech-recognition-test
          </a>
        </footer>
      </body>
    </html>
  );
}
